// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cluster.proto

package protos

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Response represents a rpc message
type Response struct {
	Code                 int32    `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=Msg,proto3" json:"Msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_cluster_95360d360239b954, []int{0}
}
func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (dst *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(dst, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Response) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

// UserMessage represents a message that user sent
type UserMessage struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Content              string   `protobuf:"bytes,2,opt,name=Content,proto3" json:"Content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserMessage) Reset()         { *m = UserMessage{} }
func (m *UserMessage) String() string { return proto.CompactTextString(m) }
func (*UserMessage) ProtoMessage()    {}
func (*UserMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_cluster_95360d360239b954, []int{1}
}
func (m *UserMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserMessage.Unmarshal(m, b)
}
func (m *UserMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserMessage.Marshal(b, m, deterministic)
}
func (dst *UserMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserMessage.Merge(dst, src)
}
func (m *UserMessage) XXX_Size() int {
	return xxx_messageInfo_UserMessage.Size(m)
}
func (m *UserMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_UserMessage.DiscardUnknown(m)
}

var xxx_messageInfo_UserMessage proto.InternalMessageInfo

func (m *UserMessage) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UserMessage) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

// NewUser message will be received when new user join room
type NewUser struct {
	Content              string   `protobuf:"bytes,1,opt,name=Content,proto3" json:"Content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewUser) Reset()         { *m = NewUser{} }
func (m *NewUser) String() string { return proto.CompactTextString(m) }
func (*NewUser) ProtoMessage()    {}
func (*NewUser) Descriptor() ([]byte, []int) {
	return fileDescriptor_cluster_95360d360239b954, []int{2}
}
func (m *NewUser) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewUser.Unmarshal(m, b)
}
func (m *NewUser) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewUser.Marshal(b, m, deterministic)
}
func (dst *NewUser) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewUser.Merge(dst, src)
}
func (m *NewUser) XXX_Size() int {
	return xxx_messageInfo_NewUser.Size(m)
}
func (m *NewUser) XXX_DiscardUnknown() {
	xxx_messageInfo_NewUser.DiscardUnknown(m)
}

var xxx_messageInfo_NewUser proto.InternalMessageInfo

func (m *NewUser) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type RPCMsg struct {
	Route                string   `protobuf:"bytes,1,opt,name=Route,proto3" json:"Route,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=Msg,proto3" json:"Msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RPCMsg) Reset()         { *m = RPCMsg{} }
func (m *RPCMsg) String() string { return proto.CompactTextString(m) }
func (*RPCMsg) ProtoMessage()    {}
func (*RPCMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_cluster_95360d360239b954, []int{3}
}
func (m *RPCMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RPCMsg.Unmarshal(m, b)
}
func (m *RPCMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RPCMsg.Marshal(b, m, deterministic)
}
func (dst *RPCMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RPCMsg.Merge(dst, src)
}
func (m *RPCMsg) XXX_Size() int {
	return xxx_messageInfo_RPCMsg.Size(m)
}
func (m *RPCMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_RPCMsg.DiscardUnknown(m)
}

var xxx_messageInfo_RPCMsg proto.InternalMessageInfo

func (m *RPCMsg) GetRoute() string {
	if m != nil {
		return m.Route
	}
	return ""
}

func (m *RPCMsg) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

// AllMembers contains all members uid
type AllMembers struct {
	Members              []string `protobuf:"bytes,1,rep,name=Members,proto3" json:"Members,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AllMembers) Reset()         { *m = AllMembers{} }
func (m *AllMembers) String() string { return proto.CompactTextString(m) }
func (*AllMembers) ProtoMessage()    {}
func (*AllMembers) Descriptor() ([]byte, []int) {
	return fileDescriptor_cluster_95360d360239b954, []int{4}
}
func (m *AllMembers) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AllMembers.Unmarshal(m, b)
}
func (m *AllMembers) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AllMembers.Marshal(b, m, deterministic)
}
func (dst *AllMembers) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AllMembers.Merge(dst, src)
}
func (m *AllMembers) XXX_Size() int {
	return xxx_messageInfo_AllMembers.Size(m)
}
func (m *AllMembers) XXX_DiscardUnknown() {
	xxx_messageInfo_AllMembers.DiscardUnknown(m)
}

var xxx_messageInfo_AllMembers proto.InternalMessageInfo

func (m *AllMembers) GetMembers() []string {
	if m != nil {
		return m.Members
	}
	return nil
}

func init() {
	proto.RegisterType((*Response)(nil), "protos.Response")
	proto.RegisterType((*UserMessage)(nil), "protos.UserMessage")
	proto.RegisterType((*NewUser)(nil), "protos.NewUser")
	proto.RegisterType((*RPCMsg)(nil), "protos.RPCMsg")
	proto.RegisterType((*AllMembers)(nil), "protos.AllMembers")
}

func init() { proto.RegisterFile("cluster.proto", fileDescriptor_cluster_95360d360239b954) }

var fileDescriptor_cluster_95360d360239b954 = []byte{
	// 192 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x8f, 0x31, 0xab, 0x83, 0x30,
	0x14, 0x85, 0xc9, 0xf3, 0xa9, 0xcf, 0xfb, 0x28, 0x94, 0xd0, 0x21, 0xa3, 0x58, 0x28, 0x4e, 0x45,
	0xe8, 0xd8, 0xa9, 0x38, 0x47, 0x4a, 0xa0, 0x3f, 0x40, 0xdb, 0x8b, 0x8b, 0x1a, 0xc9, 0x8d, 0xf4,
	0xef, 0x97, 0x44, 0x85, 0x16, 0x3a, 0xe5, 0x3b, 0x70, 0xbe, 0x43, 0x2e, 0x6c, 0xee, 0xdd, 0x44,
	0x16, 0xcd, 0x71, 0x34, 0xda, 0x6a, 0x1e, 0xf9, 0x87, 0xb2, 0x02, 0xfe, 0x14, 0xd2, 0xa8, 0x07,
	0x42, 0xce, 0xe1, 0xb7, 0xd4, 0x0f, 0x14, 0x2c, 0x65, 0x79, 0xa8, 0x3c, 0xf3, 0x2d, 0x04, 0x92,
	0x5a, 0xf1, 0x93, 0xb2, 0x3c, 0x51, 0x0e, 0xb3, 0x33, 0xfc, 0xdf, 0x08, 0x8d, 0x44, 0xa2, 0xba,
	0xf5, 0x52, 0x55, 0xf7, 0xb3, 0x94, 0x28, 0xcf, 0x5c, 0x40, 0x5c, 0xea, 0xc1, 0xe2, 0x60, 0x17,
	0x71, 0x8d, 0xd9, 0x1e, 0xe2, 0x0a, 0x9f, 0xce, 0x7f, 0x2f, 0xb1, 0xcf, 0x52, 0x01, 0x91, 0xba,
	0x96, 0x92, 0x5a, 0xbe, 0x83, 0x50, 0xe9, 0xc9, 0xae, 0xeb, 0x73, 0xf8, 0xf2, 0xa7, 0x03, 0xc0,
	0xa5, 0xeb, 0x24, 0xf6, 0x0d, 0x1a, 0x72, 0xcb, 0x0b, 0x0a, 0x96, 0x06, 0x6e, 0x79, 0x89, 0xcd,
	0x7c, 0xf5, 0xe9, 0x15, 0x00, 0x00, 0xff, 0xff, 0x9e, 0x13, 0x90, 0x17, 0x0d, 0x01, 0x00, 0x00,
}
