// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: sidecar.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace NPitaya.Protos {

  /// <summary>Holder for reflection information generated from sidecar.proto</summary>
  public static partial class SidecarReflection {

    #region Descriptor
    /// <summary>File descriptor for sidecar.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static SidecarReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg1zaWRlY2FyLnByb3RvEgZwcm90b3MaC2Vycm9yLnByb3RvGgpwdXNoLnBy",
            "b3RvGgpraWNrLnByb3RvGgltc2cucHJvdG8aDnJlc3BvbnNlLnByb3RvGg1y",
            "ZXF1ZXN0LnByb3RvGhtnb29nbGUvcHJvdG9idWYvZW1wdHkucHJvdG8ipwEK",
            "BlNlcnZlchIKCgJpZBgBIAEoCRIQCghmcm9udGVuZBgCIAEoCBIMCgR0eXBl",
            "GAMgASgJEi4KCG1ldGFkYXRhGAQgAygLMhwucHJvdG9zLlNlcnZlci5NZXRh",
            "ZGF0YUVudHJ5EhAKCGhvc3RuYW1lGAUgASgJGi8KDU1ldGFkYXRhRW50cnkS",
            "CwoDa2V5GAEgASgJEg0KBXZhbHVlGAIgASgJOgI4ASJtCgdTREV2ZW50EiQK",
            "BWV2ZW50GAEgASgOMhUucHJvdG9zLlNERXZlbnQuRXZlbnQSHgoGc2VydmVy",
            "GAIgASgLMg4ucHJvdG9zLlNlcnZlciIcCgVFdmVudBIHCgNBREQQABIKCgZS",
            "RU1PVkUQASJmChJTdGFydFBpdGF5YVJlcXVlc3QSHgoGY29uZmlnGAEgASgL",
            "Mg4ucHJvdG9zLlNlcnZlchIeChZzaG91bGRDb21wcmVzc01lc3NhZ2VzGAIg",
            "ASgIEhAKCGRlYnVnTG9nGAMgASgIIjcKCVJlcXVlc3RUbxIQCghzZXJ2ZXJJ",
            "RBgBIAEoCRIYCgNtc2cYAiABKAsyCy5wcm90b3MuTXNnIlcKC1JQQ1Jlc3Bv",
            "bnNlEg0KBXJlcUlkGAEgASgEEh0KA3JlcxgCIAEoCzIQLnByb3Rvcy5SZXNw",
            "b25zZRIaCgNlcnIYAyABKAsyDS5wcm90b3MuRXJyb3IiPQoOU2lkZWNhclJl",
            "cXVlc3QSDQoFcmVxSWQYASABKAQSHAoDcmVxGAIgASgLMg8ucHJvdG9zLlJl",
            "cXVlc3QiPwoLUHVzaFJlcXVlc3QSFAoMZnJvbnRlbmRUeXBlGAIgASgJEhoK",
            "BHB1c2gYAyABKAsyDC5wcm90b3MuUHVzaCI1CgxQdXNoUmVzcG9uc2USEgoK",
            "ZmFpbGVkVWlkcxgBIAMoCRIRCgloYXNGYWlsZWQYAiABKAgiQgoLS2lja1Jl",
            "cXVlc3QSFAoMZnJvbnRlbmRUeXBlGAIgASgJEh0KBGtpY2sYAyABKAsyDy5w",
            "cm90b3MuS2lja01zZzL1AwoHU2lkZWNhchIrCglHZXRTZXJ2ZXISDi5wcm90",
            "b3MuU2VydmVyGg4ucHJvdG9zLlNlcnZlchI7CglIZWFydGJlYXQSFi5nb29n",
            "bGUucHJvdG9idWYuRW1wdHkaFi5nb29nbGUucHJvdG9idWYuRW1wdHkSPAoJ",
            "TGlzdGVuUlBDEhMucHJvdG9zLlJQQ1Jlc3BvbnNlGhYucHJvdG9zLlNpZGVj",
            "YXJSZXF1ZXN0KAEwARI1CghMaXN0ZW5TRBIWLmdvb2dsZS5wcm90b2J1Zi5F",
            "bXB0eRoPLnByb3Rvcy5TREV2ZW50MAESLgoHU2VuZFJQQxIRLnByb3Rvcy5S",
            "ZXF1ZXN0VG8aEC5wcm90b3MuUmVzcG9uc2USNQoIU2VuZFB1c2gSEy5wcm90",
            "b3MuUHVzaFJlcXVlc3QaFC5wcm90b3MuUHVzaFJlc3BvbnNlEjUKCFNlbmRL",
            "aWNrEhMucHJvdG9zLktpY2tSZXF1ZXN0GhQucHJvdG9zLlB1c2hSZXNwb25z",
            "ZRI4CgtTdGFydFBpdGF5YRIaLnByb3Rvcy5TdGFydFBpdGF5YVJlcXVlc3Qa",
            "DS5wcm90b3MuRXJyb3ISMwoKU3RvcFBpdGF5YRIWLmdvb2dsZS5wcm90b2J1",
            "Zi5FbXB0eRoNLnByb3Rvcy5FcnJvckI8WilnaXRodWIuY29tL3RvcGZyZWVn",
            "YW1lcy9waXRheWEvcGtnL3Byb3Rvc6oCDk5QaXRheWEuUHJvdG9zYgZwcm90",
            "bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::NPitaya.Protos.ErrorReflection.Descriptor, global::NPitaya.Protos.PushReflection.Descriptor, global::NPitaya.Protos.KickReflection.Descriptor, global::NPitaya.Protos.MsgReflection.Descriptor, global::NPitaya.Protos.ResponseReflection.Descriptor, global::NPitaya.Protos.RequestReflection.Descriptor, global::Google.Protobuf.WellKnownTypes.EmptyReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::NPitaya.Protos.Server), global::NPitaya.Protos.Server.Parser, new[]{ "Id", "Frontend", "Type", "Metadata", "Hostname" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { null, }),
            new pbr::GeneratedClrTypeInfo(typeof(global::NPitaya.Protos.SDEvent), global::NPitaya.Protos.SDEvent.Parser, new[]{ "Event", "Server" }, null, new[]{ typeof(global::NPitaya.Protos.SDEvent.Types.Event) }, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::NPitaya.Protos.StartPitayaRequest), global::NPitaya.Protos.StartPitayaRequest.Parser, new[]{ "Config", "ShouldCompressMessages", "DebugLog" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::NPitaya.Protos.RequestTo), global::NPitaya.Protos.RequestTo.Parser, new[]{ "ServerID", "Msg" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::NPitaya.Protos.RPCResponse), global::NPitaya.Protos.RPCResponse.Parser, new[]{ "ReqId", "Res", "Err" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::NPitaya.Protos.SidecarRequest), global::NPitaya.Protos.SidecarRequest.Parser, new[]{ "ReqId", "Req" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::NPitaya.Protos.PushRequest), global::NPitaya.Protos.PushRequest.Parser, new[]{ "FrontendType", "Push" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::NPitaya.Protos.PushResponse), global::NPitaya.Protos.PushResponse.Parser, new[]{ "FailedUids", "HasFailed" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::NPitaya.Protos.KickRequest), global::NPitaya.Protos.KickRequest.Parser, new[]{ "FrontendType", "Kick" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class Server : pb::IMessage<Server>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Server> _parser = new pb::MessageParser<Server>(() => new Server());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Server> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::NPitaya.Protos.SidecarReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Server() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Server(Server other) : this() {
      id_ = other.id_;
      frontend_ = other.frontend_;
      type_ = other.type_;
      metadata_ = other.metadata_.Clone();
      hostname_ = other.hostname_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Server Clone() {
      return new Server(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private string id_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Id {
      get { return id_; }
      set {
        id_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "frontend" field.</summary>
    public const int FrontendFieldNumber = 2;
    private bool frontend_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Frontend {
      get { return frontend_; }
      set {
        frontend_ = value;
      }
    }

    /// <summary>Field number for the "type" field.</summary>
    public const int TypeFieldNumber = 3;
    private string type_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Type {
      get { return type_; }
      set {
        type_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "metadata" field.</summary>
    public const int MetadataFieldNumber = 4;
    private static readonly pbc::MapField<string, string>.Codec _map_metadata_codec
        = new pbc::MapField<string, string>.Codec(pb::FieldCodec.ForString(10, ""), pb::FieldCodec.ForString(18, ""), 34);
    private readonly pbc::MapField<string, string> metadata_ = new pbc::MapField<string, string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::MapField<string, string> Metadata {
      get { return metadata_; }
    }

    /// <summary>Field number for the "hostname" field.</summary>
    public const int HostnameFieldNumber = 5;
    private string hostname_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Hostname {
      get { return hostname_; }
      set {
        hostname_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Server);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Server other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (Frontend != other.Frontend) return false;
      if (Type != other.Type) return false;
      if (!Metadata.Equals(other.Metadata)) return false;
      if (Hostname != other.Hostname) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Id.Length != 0) hash ^= Id.GetHashCode();
      if (Frontend != false) hash ^= Frontend.GetHashCode();
      if (Type.Length != 0) hash ^= Type.GetHashCode();
      hash ^= Metadata.GetHashCode();
      if (Hostname.Length != 0) hash ^= Hostname.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      if (Frontend != false) {
        output.WriteRawTag(16);
        output.WriteBool(Frontend);
      }
      if (Type.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Type);
      }
      metadata_.WriteTo(output, _map_metadata_codec);
      if (Hostname.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(Hostname);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      if (Frontend != false) {
        output.WriteRawTag(16);
        output.WriteBool(Frontend);
      }
      if (Type.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Type);
      }
      metadata_.WriteTo(ref output, _map_metadata_codec);
      if (Hostname.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(Hostname);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Id.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Id);
      }
      if (Frontend != false) {
        size += 1 + 1;
      }
      if (Type.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Type);
      }
      size += metadata_.CalculateSize(_map_metadata_codec);
      if (Hostname.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Hostname);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Server other) {
      if (other == null) {
        return;
      }
      if (other.Id.Length != 0) {
        Id = other.Id;
      }
      if (other.Frontend != false) {
        Frontend = other.Frontend;
      }
      if (other.Type.Length != 0) {
        Type = other.Type;
      }
      metadata_.Add(other.metadata_);
      if (other.Hostname.Length != 0) {
        Hostname = other.Hostname;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
          case 16: {
            Frontend = input.ReadBool();
            break;
          }
          case 26: {
            Type = input.ReadString();
            break;
          }
          case 34: {
            metadata_.AddEntriesFrom(input, _map_metadata_codec);
            break;
          }
          case 42: {
            Hostname = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
          case 16: {
            Frontend = input.ReadBool();
            break;
          }
          case 26: {
            Type = input.ReadString();
            break;
          }
          case 34: {
            metadata_.AddEntriesFrom(ref input, _map_metadata_codec);
            break;
          }
          case 42: {
            Hostname = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class SDEvent : pb::IMessage<SDEvent>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<SDEvent> _parser = new pb::MessageParser<SDEvent>(() => new SDEvent());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<SDEvent> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::NPitaya.Protos.SidecarReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SDEvent() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SDEvent(SDEvent other) : this() {
      event_ = other.event_;
      server_ = other.server_ != null ? other.server_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SDEvent Clone() {
      return new SDEvent(this);
    }

    /// <summary>Field number for the "event" field.</summary>
    public const int EventFieldNumber = 1;
    private global::NPitaya.Protos.SDEvent.Types.Event event_ = global::NPitaya.Protos.SDEvent.Types.Event.Add;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::NPitaya.Protos.SDEvent.Types.Event Event {
      get { return event_; }
      set {
        event_ = value;
      }
    }

    /// <summary>Field number for the "server" field.</summary>
    public const int ServerFieldNumber = 2;
    private global::NPitaya.Protos.Server server_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::NPitaya.Protos.Server Server {
      get { return server_; }
      set {
        server_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as SDEvent);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(SDEvent other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Event != other.Event) return false;
      if (!object.Equals(Server, other.Server)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Event != global::NPitaya.Protos.SDEvent.Types.Event.Add) hash ^= Event.GetHashCode();
      if (server_ != null) hash ^= Server.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Event != global::NPitaya.Protos.SDEvent.Types.Event.Add) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Event);
      }
      if (server_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Server);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Event != global::NPitaya.Protos.SDEvent.Types.Event.Add) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Event);
      }
      if (server_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Server);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Event != global::NPitaya.Protos.SDEvent.Types.Event.Add) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Event);
      }
      if (server_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Server);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(SDEvent other) {
      if (other == null) {
        return;
      }
      if (other.Event != global::NPitaya.Protos.SDEvent.Types.Event.Add) {
        Event = other.Event;
      }
      if (other.server_ != null) {
        if (server_ == null) {
          Server = new global::NPitaya.Protos.Server();
        }
        Server.MergeFrom(other.Server);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Event = (global::NPitaya.Protos.SDEvent.Types.Event) input.ReadEnum();
            break;
          }
          case 18: {
            if (server_ == null) {
              Server = new global::NPitaya.Protos.Server();
            }
            input.ReadMessage(Server);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Event = (global::NPitaya.Protos.SDEvent.Types.Event) input.ReadEnum();
            break;
          }
          case 18: {
            if (server_ == null) {
              Server = new global::NPitaya.Protos.Server();
            }
            input.ReadMessage(Server);
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the SDEvent message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      public enum Event {
        [pbr::OriginalName("ADD")] Add = 0,
        [pbr::OriginalName("REMOVE")] Remove = 1,
      }

    }
    #endregion

  }

  public sealed partial class StartPitayaRequest : pb::IMessage<StartPitayaRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<StartPitayaRequest> _parser = new pb::MessageParser<StartPitayaRequest>(() => new StartPitayaRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<StartPitayaRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::NPitaya.Protos.SidecarReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public StartPitayaRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public StartPitayaRequest(StartPitayaRequest other) : this() {
      config_ = other.config_ != null ? other.config_.Clone() : null;
      shouldCompressMessages_ = other.shouldCompressMessages_;
      debugLog_ = other.debugLog_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public StartPitayaRequest Clone() {
      return new StartPitayaRequest(this);
    }

    /// <summary>Field number for the "config" field.</summary>
    public const int ConfigFieldNumber = 1;
    private global::NPitaya.Protos.Server config_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::NPitaya.Protos.Server Config {
      get { return config_; }
      set {
        config_ = value;
      }
    }

    /// <summary>Field number for the "shouldCompressMessages" field.</summary>
    public const int ShouldCompressMessagesFieldNumber = 2;
    private bool shouldCompressMessages_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool ShouldCompressMessages {
      get { return shouldCompressMessages_; }
      set {
        shouldCompressMessages_ = value;
      }
    }

    /// <summary>Field number for the "debugLog" field.</summary>
    public const int DebugLogFieldNumber = 3;
    private bool debugLog_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool DebugLog {
      get { return debugLog_; }
      set {
        debugLog_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as StartPitayaRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(StartPitayaRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Config, other.Config)) return false;
      if (ShouldCompressMessages != other.ShouldCompressMessages) return false;
      if (DebugLog != other.DebugLog) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (config_ != null) hash ^= Config.GetHashCode();
      if (ShouldCompressMessages != false) hash ^= ShouldCompressMessages.GetHashCode();
      if (DebugLog != false) hash ^= DebugLog.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (config_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Config);
      }
      if (ShouldCompressMessages != false) {
        output.WriteRawTag(16);
        output.WriteBool(ShouldCompressMessages);
      }
      if (DebugLog != false) {
        output.WriteRawTag(24);
        output.WriteBool(DebugLog);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (config_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Config);
      }
      if (ShouldCompressMessages != false) {
        output.WriteRawTag(16);
        output.WriteBool(ShouldCompressMessages);
      }
      if (DebugLog != false) {
        output.WriteRawTag(24);
        output.WriteBool(DebugLog);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (config_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Config);
      }
      if (ShouldCompressMessages != false) {
        size += 1 + 1;
      }
      if (DebugLog != false) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(StartPitayaRequest other) {
      if (other == null) {
        return;
      }
      if (other.config_ != null) {
        if (config_ == null) {
          Config = new global::NPitaya.Protos.Server();
        }
        Config.MergeFrom(other.Config);
      }
      if (other.ShouldCompressMessages != false) {
        ShouldCompressMessages = other.ShouldCompressMessages;
      }
      if (other.DebugLog != false) {
        DebugLog = other.DebugLog;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (config_ == null) {
              Config = new global::NPitaya.Protos.Server();
            }
            input.ReadMessage(Config);
            break;
          }
          case 16: {
            ShouldCompressMessages = input.ReadBool();
            break;
          }
          case 24: {
            DebugLog = input.ReadBool();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (config_ == null) {
              Config = new global::NPitaya.Protos.Server();
            }
            input.ReadMessage(Config);
            break;
          }
          case 16: {
            ShouldCompressMessages = input.ReadBool();
            break;
          }
          case 24: {
            DebugLog = input.ReadBool();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class RequestTo : pb::IMessage<RequestTo>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<RequestTo> _parser = new pb::MessageParser<RequestTo>(() => new RequestTo());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<RequestTo> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::NPitaya.Protos.SidecarReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RequestTo() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RequestTo(RequestTo other) : this() {
      serverID_ = other.serverID_;
      msg_ = other.msg_ != null ? other.msg_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RequestTo Clone() {
      return new RequestTo(this);
    }

    /// <summary>Field number for the "serverID" field.</summary>
    public const int ServerIDFieldNumber = 1;
    private string serverID_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string ServerID {
      get { return serverID_; }
      set {
        serverID_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "msg" field.</summary>
    public const int MsgFieldNumber = 2;
    private global::NPitaya.Protos.Msg msg_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::NPitaya.Protos.Msg Msg {
      get { return msg_; }
      set {
        msg_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as RequestTo);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(RequestTo other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ServerID != other.ServerID) return false;
      if (!object.Equals(Msg, other.Msg)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (ServerID.Length != 0) hash ^= ServerID.GetHashCode();
      if (msg_ != null) hash ^= Msg.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (ServerID.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(ServerID);
      }
      if (msg_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Msg);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (ServerID.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(ServerID);
      }
      if (msg_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Msg);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (ServerID.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ServerID);
      }
      if (msg_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Msg);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(RequestTo other) {
      if (other == null) {
        return;
      }
      if (other.ServerID.Length != 0) {
        ServerID = other.ServerID;
      }
      if (other.msg_ != null) {
        if (msg_ == null) {
          Msg = new global::NPitaya.Protos.Msg();
        }
        Msg.MergeFrom(other.Msg);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            ServerID = input.ReadString();
            break;
          }
          case 18: {
            if (msg_ == null) {
              Msg = new global::NPitaya.Protos.Msg();
            }
            input.ReadMessage(Msg);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            ServerID = input.ReadString();
            break;
          }
          case 18: {
            if (msg_ == null) {
              Msg = new global::NPitaya.Protos.Msg();
            }
            input.ReadMessage(Msg);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class RPCResponse : pb::IMessage<RPCResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<RPCResponse> _parser = new pb::MessageParser<RPCResponse>(() => new RPCResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<RPCResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::NPitaya.Protos.SidecarReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RPCResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RPCResponse(RPCResponse other) : this() {
      reqId_ = other.reqId_;
      res_ = other.res_ != null ? other.res_.Clone() : null;
      err_ = other.err_ != null ? other.err_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RPCResponse Clone() {
      return new RPCResponse(this);
    }

    /// <summary>Field number for the "reqId" field.</summary>
    public const int ReqIdFieldNumber = 1;
    private ulong reqId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ulong ReqId {
      get { return reqId_; }
      set {
        reqId_ = value;
      }
    }

    /// <summary>Field number for the "res" field.</summary>
    public const int ResFieldNumber = 2;
    private global::NPitaya.Protos.Response res_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::NPitaya.Protos.Response Res {
      get { return res_; }
      set {
        res_ = value;
      }
    }

    /// <summary>Field number for the "err" field.</summary>
    public const int ErrFieldNumber = 3;
    private global::NPitaya.Protos.Error err_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::NPitaya.Protos.Error Err {
      get { return err_; }
      set {
        err_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as RPCResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(RPCResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ReqId != other.ReqId) return false;
      if (!object.Equals(Res, other.Res)) return false;
      if (!object.Equals(Err, other.Err)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (ReqId != 0UL) hash ^= ReqId.GetHashCode();
      if (res_ != null) hash ^= Res.GetHashCode();
      if (err_ != null) hash ^= Err.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (ReqId != 0UL) {
        output.WriteRawTag(8);
        output.WriteUInt64(ReqId);
      }
      if (res_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Res);
      }
      if (err_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Err);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (ReqId != 0UL) {
        output.WriteRawTag(8);
        output.WriteUInt64(ReqId);
      }
      if (res_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Res);
      }
      if (err_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Err);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (ReqId != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(ReqId);
      }
      if (res_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Res);
      }
      if (err_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Err);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(RPCResponse other) {
      if (other == null) {
        return;
      }
      if (other.ReqId != 0UL) {
        ReqId = other.ReqId;
      }
      if (other.res_ != null) {
        if (res_ == null) {
          Res = new global::NPitaya.Protos.Response();
        }
        Res.MergeFrom(other.Res);
      }
      if (other.err_ != null) {
        if (err_ == null) {
          Err = new global::NPitaya.Protos.Error();
        }
        Err.MergeFrom(other.Err);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            ReqId = input.ReadUInt64();
            break;
          }
          case 18: {
            if (res_ == null) {
              Res = new global::NPitaya.Protos.Response();
            }
            input.ReadMessage(Res);
            break;
          }
          case 26: {
            if (err_ == null) {
              Err = new global::NPitaya.Protos.Error();
            }
            input.ReadMessage(Err);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            ReqId = input.ReadUInt64();
            break;
          }
          case 18: {
            if (res_ == null) {
              Res = new global::NPitaya.Protos.Response();
            }
            input.ReadMessage(Res);
            break;
          }
          case 26: {
            if (err_ == null) {
              Err = new global::NPitaya.Protos.Error();
            }
            input.ReadMessage(Err);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class SidecarRequest : pb::IMessage<SidecarRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<SidecarRequest> _parser = new pb::MessageParser<SidecarRequest>(() => new SidecarRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<SidecarRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::NPitaya.Protos.SidecarReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SidecarRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SidecarRequest(SidecarRequest other) : this() {
      reqId_ = other.reqId_;
      req_ = other.req_ != null ? other.req_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SidecarRequest Clone() {
      return new SidecarRequest(this);
    }

    /// <summary>Field number for the "reqId" field.</summary>
    public const int ReqIdFieldNumber = 1;
    private ulong reqId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ulong ReqId {
      get { return reqId_; }
      set {
        reqId_ = value;
      }
    }

    /// <summary>Field number for the "req" field.</summary>
    public const int ReqFieldNumber = 2;
    private global::NPitaya.Protos.Request req_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::NPitaya.Protos.Request Req {
      get { return req_; }
      set {
        req_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as SidecarRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(SidecarRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ReqId != other.ReqId) return false;
      if (!object.Equals(Req, other.Req)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (ReqId != 0UL) hash ^= ReqId.GetHashCode();
      if (req_ != null) hash ^= Req.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (ReqId != 0UL) {
        output.WriteRawTag(8);
        output.WriteUInt64(ReqId);
      }
      if (req_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Req);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (ReqId != 0UL) {
        output.WriteRawTag(8);
        output.WriteUInt64(ReqId);
      }
      if (req_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Req);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (ReqId != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(ReqId);
      }
      if (req_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Req);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(SidecarRequest other) {
      if (other == null) {
        return;
      }
      if (other.ReqId != 0UL) {
        ReqId = other.ReqId;
      }
      if (other.req_ != null) {
        if (req_ == null) {
          Req = new global::NPitaya.Protos.Request();
        }
        Req.MergeFrom(other.Req);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            ReqId = input.ReadUInt64();
            break;
          }
          case 18: {
            if (req_ == null) {
              Req = new global::NPitaya.Protos.Request();
            }
            input.ReadMessage(Req);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            ReqId = input.ReadUInt64();
            break;
          }
          case 18: {
            if (req_ == null) {
              Req = new global::NPitaya.Protos.Request();
            }
            input.ReadMessage(Req);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class PushRequest : pb::IMessage<PushRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<PushRequest> _parser = new pb::MessageParser<PushRequest>(() => new PushRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<PushRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::NPitaya.Protos.SidecarReflection.Descriptor.MessageTypes[6]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PushRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PushRequest(PushRequest other) : this() {
      frontendType_ = other.frontendType_;
      push_ = other.push_ != null ? other.push_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PushRequest Clone() {
      return new PushRequest(this);
    }

    /// <summary>Field number for the "frontendType" field.</summary>
    public const int FrontendTypeFieldNumber = 2;
    private string frontendType_ = "";
    /// <summary>
    /// TODO I think this field is not needed if we use nats only
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string FrontendType {
      get { return frontendType_; }
      set {
        frontendType_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "push" field.</summary>
    public const int PushFieldNumber = 3;
    private global::NPitaya.Protos.Push push_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::NPitaya.Protos.Push Push {
      get { return push_; }
      set {
        push_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as PushRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(PushRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (FrontendType != other.FrontendType) return false;
      if (!object.Equals(Push, other.Push)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (FrontendType.Length != 0) hash ^= FrontendType.GetHashCode();
      if (push_ != null) hash ^= Push.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (FrontendType.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(FrontendType);
      }
      if (push_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Push);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (FrontendType.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(FrontendType);
      }
      if (push_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Push);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (FrontendType.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(FrontendType);
      }
      if (push_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Push);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(PushRequest other) {
      if (other == null) {
        return;
      }
      if (other.FrontendType.Length != 0) {
        FrontendType = other.FrontendType;
      }
      if (other.push_ != null) {
        if (push_ == null) {
          Push = new global::NPitaya.Protos.Push();
        }
        Push.MergeFrom(other.Push);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 18: {
            FrontendType = input.ReadString();
            break;
          }
          case 26: {
            if (push_ == null) {
              Push = new global::NPitaya.Protos.Push();
            }
            input.ReadMessage(Push);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 18: {
            FrontendType = input.ReadString();
            break;
          }
          case 26: {
            if (push_ == null) {
              Push = new global::NPitaya.Protos.Push();
            }
            input.ReadMessage(Push);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class PushResponse : pb::IMessage<PushResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<PushResponse> _parser = new pb::MessageParser<PushResponse>(() => new PushResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<PushResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::NPitaya.Protos.SidecarReflection.Descriptor.MessageTypes[7]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PushResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PushResponse(PushResponse other) : this() {
      failedUids_ = other.failedUids_.Clone();
      hasFailed_ = other.hasFailed_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PushResponse Clone() {
      return new PushResponse(this);
    }

    /// <summary>Field number for the "failedUids" field.</summary>
    public const int FailedUidsFieldNumber = 1;
    private static readonly pb::FieldCodec<string> _repeated_failedUids_codec
        = pb::FieldCodec.ForString(10);
    private readonly pbc::RepeatedField<string> failedUids_ = new pbc::RepeatedField<string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<string> FailedUids {
      get { return failedUids_; }
    }

    /// <summary>Field number for the "hasFailed" field.</summary>
    public const int HasFailedFieldNumber = 2;
    private bool hasFailed_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasFailed {
      get { return hasFailed_; }
      set {
        hasFailed_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as PushResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(PushResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!failedUids_.Equals(other.failedUids_)) return false;
      if (HasFailed != other.HasFailed) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= failedUids_.GetHashCode();
      if (HasFailed != false) hash ^= HasFailed.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      failedUids_.WriteTo(output, _repeated_failedUids_codec);
      if (HasFailed != false) {
        output.WriteRawTag(16);
        output.WriteBool(HasFailed);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      failedUids_.WriteTo(ref output, _repeated_failedUids_codec);
      if (HasFailed != false) {
        output.WriteRawTag(16);
        output.WriteBool(HasFailed);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += failedUids_.CalculateSize(_repeated_failedUids_codec);
      if (HasFailed != false) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(PushResponse other) {
      if (other == null) {
        return;
      }
      failedUids_.Add(other.failedUids_);
      if (other.HasFailed != false) {
        HasFailed = other.HasFailed;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            failedUids_.AddEntriesFrom(input, _repeated_failedUids_codec);
            break;
          }
          case 16: {
            HasFailed = input.ReadBool();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            failedUids_.AddEntriesFrom(ref input, _repeated_failedUids_codec);
            break;
          }
          case 16: {
            HasFailed = input.ReadBool();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class KickRequest : pb::IMessage<KickRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<KickRequest> _parser = new pb::MessageParser<KickRequest>(() => new KickRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<KickRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::NPitaya.Protos.SidecarReflection.Descriptor.MessageTypes[8]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public KickRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public KickRequest(KickRequest other) : this() {
      frontendType_ = other.frontendType_;
      kick_ = other.kick_ != null ? other.kick_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public KickRequest Clone() {
      return new KickRequest(this);
    }

    /// <summary>Field number for the "frontendType" field.</summary>
    public const int FrontendTypeFieldNumber = 2;
    private string frontendType_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string FrontendType {
      get { return frontendType_; }
      set {
        frontendType_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "kick" field.</summary>
    public const int KickFieldNumber = 3;
    private global::NPitaya.Protos.KickMsg kick_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::NPitaya.Protos.KickMsg Kick {
      get { return kick_; }
      set {
        kick_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as KickRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(KickRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (FrontendType != other.FrontendType) return false;
      if (!object.Equals(Kick, other.Kick)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (FrontendType.Length != 0) hash ^= FrontendType.GetHashCode();
      if (kick_ != null) hash ^= Kick.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (FrontendType.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(FrontendType);
      }
      if (kick_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Kick);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (FrontendType.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(FrontendType);
      }
      if (kick_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Kick);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (FrontendType.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(FrontendType);
      }
      if (kick_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Kick);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(KickRequest other) {
      if (other == null) {
        return;
      }
      if (other.FrontendType.Length != 0) {
        FrontendType = other.FrontendType;
      }
      if (other.kick_ != null) {
        if (kick_ == null) {
          Kick = new global::NPitaya.Protos.KickMsg();
        }
        Kick.MergeFrom(other.Kick);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 18: {
            FrontendType = input.ReadString();
            break;
          }
          case 26: {
            if (kick_ == null) {
              Kick = new global::NPitaya.Protos.KickMsg();
            }
            input.ReadMessage(Kick);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 18: {
            FrontendType = input.ReadString();
            break;
          }
          case 26: {
            if (kick_ == null) {
              Kick = new global::NPitaya.Protos.KickMsg();
            }
            input.ReadMessage(Kick);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
