// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pitaya.proto

/*
Package protos is a generated protocol buffer package.

It is generated from these files:
	pitaya.proto

It has these top-level messages:
	Push
	Session
	Msg
	Request
	Response
	Error
*/
package protos

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RPCType int32

const (
	RPCType_Sys  RPCType = 0
	RPCType_User RPCType = 1
)

var RPCType_name = map[int32]string{
	0: "Sys",
	1: "User",
}
var RPCType_value = map[string]int32{
	"Sys":  0,
	"User": 1,
}

func (x RPCType) String() string {
	return proto.EnumName(RPCType_name, int32(x))
}
func (RPCType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type MsgType int32

const (
	MsgType_MsgRequest  MsgType = 0
	MsgType_MsgNotify   MsgType = 1
	MsgType_MsgResponse MsgType = 2
	MsgType_MsgPush     MsgType = 3
)

var MsgType_name = map[int32]string{
	0: "MsgRequest",
	1: "MsgNotify",
	2: "MsgResponse",
	3: "MsgPush",
}
var MsgType_value = map[string]int32{
	"MsgRequest":  0,
	"MsgNotify":   1,
	"MsgResponse": 2,
	"MsgPush":     3,
}

func (x MsgType) String() string {
	return proto.EnumName(MsgType_name, int32(x))
}
func (MsgType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type Push struct {
	Route string `protobuf:"bytes,1,opt,name=Route" json:"Route,omitempty"`
	Uid   string `protobuf:"bytes,2,opt,name=Uid" json:"Uid,omitempty"`
	Data  []byte `protobuf:"bytes,3,opt,name=Data,proto3" json:"Data,omitempty"`
}

func (m *Push) Reset()                    { *m = Push{} }
func (m *Push) String() string            { return proto.CompactTextString(m) }
func (*Push) ProtoMessage()               {}
func (*Push) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Push) GetRoute() string {
	if m != nil {
		return m.Route
	}
	return ""
}

func (m *Push) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *Push) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type Session struct {
	ID   int64  `protobuf:"varint,1,opt,name=ID" json:"ID,omitempty"`
	Uid  string `protobuf:"bytes,2,opt,name=Uid" json:"Uid,omitempty"`
	Data []byte `protobuf:"bytes,3,opt,name=Data,proto3" json:"Data,omitempty"`
}

func (m *Session) Reset()                    { *m = Session{} }
func (m *Session) String() string            { return proto.CompactTextString(m) }
func (*Session) ProtoMessage()               {}
func (*Session) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Session) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Session) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *Session) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type Msg struct {
	ID    uint64  `protobuf:"varint,1,opt,name=ID" json:"ID,omitempty"`
	Route string  `protobuf:"bytes,2,opt,name=Route" json:"Route,omitempty"`
	Data  []byte  `protobuf:"bytes,3,opt,name=Data,proto3" json:"Data,omitempty"`
	Reply string  `protobuf:"bytes,4,opt,name=Reply" json:"Reply,omitempty"`
	Type  MsgType `protobuf:"varint,5,opt,name=Type,enum=protos.MsgType" json:"Type,omitempty"`
}

func (m *Msg) Reset()                    { *m = Msg{} }
func (m *Msg) String() string            { return proto.CompactTextString(m) }
func (*Msg) ProtoMessage()               {}
func (*Msg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Msg) GetID() uint64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Msg) GetRoute() string {
	if m != nil {
		return m.Route
	}
	return ""
}

func (m *Msg) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Msg) GetReply() string {
	if m != nil {
		return m.Reply
	}
	return ""
}

func (m *Msg) GetType() MsgType {
	if m != nil {
		return m.Type
	}
	return MsgType_MsgRequest
}

type Request struct {
	Type       RPCType  `protobuf:"varint,1,opt,name=Type,enum=protos.RPCType" json:"Type,omitempty"`
	Session    *Session `protobuf:"bytes,2,opt,name=Session" json:"Session,omitempty"`
	Msg        *Msg     `protobuf:"bytes,3,opt,name=Msg" json:"Msg,omitempty"`
	FrontendID string   `protobuf:"bytes,4,opt,name=FrontendID" json:"FrontendID,omitempty"`
}

func (m *Request) Reset()                    { *m = Request{} }
func (m *Request) String() string            { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()               {}
func (*Request) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Request) GetType() RPCType {
	if m != nil {
		return m.Type
	}
	return RPCType_Sys
}

func (m *Request) GetSession() *Session {
	if m != nil {
		return m.Session
	}
	return nil
}

func (m *Request) GetMsg() *Msg {
	if m != nil {
		return m.Msg
	}
	return nil
}

func (m *Request) GetFrontendID() string {
	if m != nil {
		return m.FrontendID
	}
	return ""
}

type Response struct {
	Data  []byte `protobuf:"bytes,1,opt,name=Data,proto3" json:"Data,omitempty"`
	Error string `protobuf:"bytes,2,opt,name=Error" json:"Error,omitempty"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Response) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Response) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type Error struct {
	Code     string            `protobuf:"bytes,1,opt,name=Code" json:"Code,omitempty"`
	Msg      string            `protobuf:"bytes,2,opt,name=Msg" json:"Msg,omitempty"`
	Metadata map[string]string `protobuf:"bytes,3,rep,name=Metadata" json:"Metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *Error) Reset()                    { *m = Error{} }
func (m *Error) String() string            { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()               {}
func (*Error) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *Error) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *Error) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *Error) GetMetadata() map[string]string {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func init() {
	proto.RegisterType((*Push)(nil), "protos.Push")
	proto.RegisterType((*Session)(nil), "protos.Session")
	proto.RegisterType((*Msg)(nil), "protos.Msg")
	proto.RegisterType((*Request)(nil), "protos.Request")
	proto.RegisterType((*Response)(nil), "protos.Response")
	proto.RegisterType((*Error)(nil), "protos.Error")
	proto.RegisterEnum("protos.RPCType", RPCType_name, RPCType_value)
	proto.RegisterEnum("protos.MsgType", MsgType_name, MsgType_value)
}

func init() { proto.RegisterFile("pitaya.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 412 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0xcd, 0xce, 0x93, 0x40,
	0x14, 0xfd, 0x06, 0xf8, 0xa4, 0xbd, 0xf4, 0x87, 0x4c, 0x5c, 0x10, 0xff, 0xd2, 0xe0, 0x06, 0xbb,
	0xe8, 0xa2, 0x9a, 0x68, 0x74, 0x61, 0x62, 0x69, 0x93, 0x2e, 0x30, 0xcd, 0xd4, 0x3e, 0x00, 0x86,
	0xb1, 0x12, 0x1b, 0x06, 0x99, 0xc1, 0x04, 0x9f, 0xc4, 0xbd, 0x2f, 0x6a, 0xe6, 0x32, 0x50, 0x9a,
	0xb8, 0xf8, 0x56, 0xdc, 0xbf, 0x73, 0x39, 0xf7, 0x9c, 0x81, 0x49, 0x99, 0xab, 0xb4, 0x49, 0x57,
	0x65, 0x25, 0x94, 0xa0, 0x8f, 0xf0, 0x23, 0xc3, 0x4f, 0xe0, 0x1c, 0x6a, 0xf9, 0x9d, 0x3e, 0x86,
	0x7b, 0x26, 0x6a, 0xc5, 0x03, 0xb2, 0x20, 0xd1, 0x98, 0xb5, 0x09, 0xf5, 0xc1, 0x3e, 0xe5, 0x59,
	0x60, 0x61, 0x4d, 0x87, 0x94, 0x82, 0x13, 0xa7, 0x2a, 0x0d, 0xec, 0x05, 0x89, 0x26, 0x0c, 0xe3,
	0xf0, 0x23, 0xb8, 0x47, 0x2e, 0x65, 0x2e, 0x0a, 0x3a, 0x03, 0x6b, 0x1f, 0xe3, 0x0e, 0x9b, 0x59,
	0xfb, 0xf8, 0x81, 0x0b, 0x7e, 0x83, 0x9d, 0xc8, 0xf3, 0x00, 0xec, 0x20, 0xb8, 0xe7, 0x64, 0x0d,
	0x39, 0xfd, 0x67, 0x01, 0x4e, 0xf2, 0xf2, 0xd2, 0x04, 0x8e, 0x99, 0xd4, 0x09, 0x7d, 0x09, 0xce,
	0x97, 0xa6, 0xe4, 0xc1, 0xfd, 0x82, 0x44, 0xb3, 0xf5, 0xbc, 0xbd, 0x5c, 0xae, 0x12, 0x79, 0xd6,
	0x65, 0x86, 0xcd, 0xf0, 0x0f, 0x01, 0x97, 0xf1, 0x9f, 0x35, 0x97, 0xaa, 0x07, 0x90, 0x5b, 0x00,
	0x3b, 0x6c, 0xae, 0x00, 0xfa, 0xaa, 0xbf, 0x16, 0x79, 0x79, 0xd7, 0x39, 0x53, 0x66, 0xbd, 0x1a,
	0xcf, 0xf1, 0x2e, 0x64, 0xea, 0xad, 0xbd, 0xc1, 0xff, 0x19, 0xde, 0xfb, 0x02, 0x60, 0x57, 0x89,
	0x42, 0xf1, 0x22, 0xdb, 0xc7, 0x86, 0xfa, 0xa0, 0x12, 0xbe, 0x81, 0x11, 0xe3, 0xb2, 0x14, 0x85,
	0xbc, 0x5e, 0x4d, 0x6e, 0xaf, 0xde, 0x56, 0x95, 0xa8, 0x3a, 0x7d, 0x30, 0x09, 0xff, 0x12, 0x53,
	0xd6, 0x98, 0x8d, 0xc8, 0x3a, 0x4b, 0x31, 0xd6, 0x86, 0x68, 0x4a, 0xc6, 0x10, 0xcd, 0xe2, 0x2d,
	0x8c, 0x12, 0xae, 0xd2, 0xac, 0xd5, 0xd4, 0x8e, 0xbc, 0xf5, 0xd3, 0x8e, 0x29, 0xae, 0x59, 0x75,
	0xdd, 0x6d, 0xa1, 0xaa, 0x86, 0xf5, 0xc3, 0x4f, 0x3e, 0xc0, 0xf4, 0xa6, 0xa5, 0x77, 0xff, 0xe0,
	0x8d, 0xf9, 0x9d, 0x0e, 0x35, 0xc3, 0x5f, 0xe9, 0xa5, 0xee, 0x1d, 0xc4, 0xe4, 0xbd, 0xf5, 0x8e,
	0x2c, 0x9f, 0x81, 0x6b, 0x64, 0xa5, 0x2e, 0xd8, 0xc7, 0x46, 0xfa, 0x77, 0x74, 0x04, 0xce, 0x49,
	0xf2, 0xca, 0x27, 0xcb, 0x1d, 0xb8, 0xc6, 0x25, 0x3a, 0x03, 0xd0, 0x82, 0xb5, 0x0e, 0xf9, 0x77,
	0x74, 0x0a, 0xe3, 0x44, 0x9e, 0x3f, 0x0b, 0x95, 0x7f, 0x6b, 0x7c, 0x42, 0xe7, 0xe0, 0x61, 0xbb,
	0x95, 0xc9, 0xb7, 0xa8, 0x87, 0x50, 0xfd, 0xa6, 0x7d, 0xfb, 0x6b, 0xfb, 0xca, 0x5f, 0xff, 0x0b,
	0x00, 0x00, 0xff, 0xff, 0x4e, 0xd9, 0x89, 0x48, 0xfc, 0x02, 0x00, 0x00,
}
