// Code generated by MockGen. DO NOT EDIT.
// Source: ./metrics/statsd_reporter.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockClient is a mock of Client interface
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
}

// MockClientMockRecorder is the mock recorder for MockClient
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// Count mocks base method
func (m *MockClient) Count(name string, value int64, tags []string, rate float64) error {
	ret := m.ctrl.Call(m, "Count", name, value, tags, rate)
	ret0, _ := ret[0].(error)
	return ret0
}

// Count indicates an expected call of Count
func (mr *MockClientMockRecorder) Count(name, value, tags, rate interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*MockClient)(nil).Count), name, value, tags, rate)
}

// Gauge mocks base method
func (m *MockClient) Gauge(name string, value float64, tags []string, rate float64) error {
	ret := m.ctrl.Call(m, "Gauge", name, value, tags, rate)
	ret0, _ := ret[0].(error)
	return ret0
}

// Gauge indicates an expected call of Gauge
func (mr *MockClientMockRecorder) Gauge(name, value, tags, rate interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Gauge", reflect.TypeOf((*MockClient)(nil).Gauge), name, value, tags, rate)
}

// TimeInMilliseconds mocks base method
func (m *MockClient) TimeInMilliseconds(name string, value float64, tags []string, rate float64) error {
	ret := m.ctrl.Call(m, "TimeInMilliseconds", name, value, tags, rate)
	ret0, _ := ret[0].(error)
	return ret0
}

// TimeInMilliseconds indicates an expected call of TimeInMilliseconds
func (mr *MockClientMockRecorder) TimeInMilliseconds(name, value, tags, rate interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TimeInMilliseconds", reflect.TypeOf((*MockClient)(nil).TimeInMilliseconds), name, value, tags, rate)
}
